const domen = 'https://api.evendor.app';
//const domen = 'http://evendors.host';
export const url = {
    
    groupItem: <string> `${domen}/api/groupsitem.php`,
    userItems: <string> `${domen}/api/userlist.php`,
    userListForOrder: <string> `${domen}/api/userlistfororder.php`,
    vendor: <string> `${domen}/api/vendor`,
    vendors: <string> `${domen}/api/vendors`,
    order1: <string> `${domen}/api/order.php`,
    vendorNote: <string> `${domen}/api/vendornote.php`,
    suspend1: <string> `${domen}/api/suspend.php`,
    login: <string> `${domen}/api/login.php`,
    signup: <string> `${domen}/api/user`,
    signin: <string> `${domen}/api/user/signin`,
    recipients: <string> `${domen}/api/recipients`,
    recipient: <string> `${domen}/api/recipient`,
    allitems: <string> `${domen}/api/items/all`,
    items: <string> `${domen}/api/items`,
    useritems: <string> `${domen}/api/useritems`,
    useritem: <string> `${domen}/api/useritem`,
    accountactivation: <string> `${domen}/api/accountactivation`,
    groups: <string> `${domen}/api/groups`,
    group: <string> `${domen}/api/group`,
    customitem: <string> `${domen}/api/customitem`,
    order: <string> `${domen}/api/order`,
    orders: <string> `${domen}/api/orders`,
    lastorders: <string> `${domen}/api/lastorders`,
    orderlist: <string> `${domen}/api/orderlist`,
    orderlistforupdate: <string> `${domen}/api/orderlistforupdate`,
    orderupdate: <string> `${domen}/api/orderupdate`,
    suspend: <string> `${domen}/api/suspendedorder`,
    updatesuspend: <string> `${domen}/api/updatesuspendedorder`,
    itemsnote: <string> `${domen}/api/itemsnote`,
    accounts: <string> `${domen}/api/accounts`,
    passvalidation: <string> `${domen}/api/passvalidation`,
    loginedit: <string> `${domen}/api/loginedit`,
    compare: <string> `${domen}/api/compare`,
    getprice: <string> `${domen}/api/getprice`,
    reviewprice: <string> `${domen}/api/reviewprice`,
    sendprice: <string> `${domen}/api/sendprice`,
    copylist: <string> `${domen}/api/copylist`
}
